name: server-proxy
on:
  push:
    branches:
      - master
  pull_request:


jobs:
  golangci:
    name: server-proxy-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ./server-proxy
          skip-save-cache: true
          args: --timeout 5m
  
  securego:
    name: server-proxy-securego
    runs-on: ubuntu-latest
    # env:
    #   GO111MODULE: on
    
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5

  #     - name: Install gosecurego
  #       run: curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

  #     - name: Run gosec
  #       run: |
  #         cd server-proxy
  #         gosec ./...