name: server-proxy
on:
  push:
    branches:
      - master
  pull_request:


jobs:
  golangci:
    name: server-proxy-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ./server-proxy
          skip-save-cache: true
          args: --timeout 5m
  
  securego:
    runs-on: ubuntu-latest
    # env:
    #   GO111MODULE: on
    
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version:
            - '1.23'
      - name: Install gosecurego
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run gosec
        run: |
          cd server-proxy
          gosec ./...